language: node_js
node_js:
  - "5.0"
after_script:
  - npm run-script test
env:
  - NODE_ENV="travis"
services: mongodb
compiler: clang-3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

