import React, {Component} from 'react';
import AltContainer from 'alt/AltContainer';

let countries = [
  { flag:"af" , name:"Afghanistan" },
  { flag:"ax" , name:"Aland Islands" },
  { flag:"al" , name:"Albania" },
  { flag:"dz" , name:"Algeria" },
  { flag:"as" , name:"American Samoa" },
  { flag:"ad" , name:"Andorra" },
  { flag:"ao" , name:"Angola" },
  { flag:"ai" , name:"Anguilla" },
  { flag:"ag" , name:"Antigua" },
  { flag:"ar" , name:"Argentina" },
  { flag:"am" , name:"Armenia" },
  { flag:"aw" , name:"Aruba" },
  { flag:"au" , name:"Australia" },
  { flag:"at" , name:"Austria" },
  { flag:"az" , name:"Azerbaijan" },
  { flag:"bs" , name:"Bahamas" },
  { flag:"bh" , name:"Bahrain" },
  { flag:"bd" , name:"Bangladesh" },
  { flag:"bb" , name:"Barbados" },
  { flag:"by" , name:"Belarus" },
  { flag:"be" , name:"Belgium" },
  { flag:"bz" , name:"Belize" },
  { flag:"bj" , name:"Benin" },
  { flag:"bm" , name:"Bermuda" },
  { flag:"bt" , name:"Bhutan" },
  { flag:"bo" , name:"Bolivia" },
  { flag:"ba" , name:"Bosnia" },
  { flag:"bw" , name:"Botswana" },
  { flag:"bv" , name:"Bouvet Island" },
  { flag:"br" , name:"Brazil" },
  { flag:"vg" , name:"British Virgin Islands" },
  { flag:"bn" , name:"Brunei" },
  { flag:"bg" , name:"Bulgaria" },
  { flag:"bf" , name:"Burkina Faso" },
  //{ flag:"br" , name:"Burma" },
  { flag:"bi" , name:"Burundi" },
  { flag:"tc" , name:"Caicos Islands" },
  { flag:"kh" , name:"Cambodia" },
  { flag:"cm" , name:"Cameroon" },
  { flag:"ca" , name:"Canada" },
  { flag:"cv" , name:"Cape Verde" },
  { flag:"ky" , name:"Cayman Islands" },
  { flag:"cf" , name:"Central African Republic" },
  { flag:"td" , name:"Chad" },
  { flag:"cl" , name:"Chile" },
  { flag:"cn" , name:"China" },
  { flag:"cx" , name:"Christmas Island" },
  { flag:"cc" , name:"Cocos Islands" },
  { flag:"co" , name:"Colombia" },
  { flag:"km" , name:"Comoros" },
  { flag:"cg" , name:"Congo Brazzaville" },
  { flag:"cd" , name:"Congo" },
  { flag:"ck" , name:"Cook Islands" },
  { flag:"cr" , name:"Costa Rica" },
  { flag:"ci" , name:"Cote Divoire" },
  { flag:"hr" , name:"Croatia" },
  { flag:"cu" , name:"Cuba" },
  { flag:"cy" , name:"Cyprus" },
  { flag:"cz" , name:"Czech Republic" },
  { flag:"dk" , name:"Denmark" },
  { flag:"dj" , name:"Djibouti" },
  { flag:"dm" , name:"Dominica" },
  { flag:"do" , name:"Dominican Republic" },
  { flag:"ec" , name:"Ecuador" },
  { flag:"eg" , name:"Egypt" },
  { flag:"sv" , name:"El Salvador" },
  { flag:"gb" , name:"England" },
  { flag:"gq" , name:"Equatorial Guinea" },
  { flag:"er" , name:"Eritrea" },
  { flag:"ee" , name:"Estonia" },
  { flag:"et" , name:"Ethiopia" },
  { flag:"eu" , name:"European Union" },
  { flag:"fk" , name:"Falkland Islands" },
  { flag:"fo" , name:"Faroe Islands" },
  { flag:"fj" , name:"Fiji" },
  { flag:"fi" , name:"Finland" },
  { flag:"fr" , name:"France" },
  { flag:"gf" , name:"French Guiana" },
  { flag:"pf" , name:"French Polynesia" },
  { flag:"tf" , name:"French Territories" },
  { flag:"ga" , name:"Gabon" },
  { flag:"gm" , name:"Gambia" },
  { flag:"ge" , name:"Georgia" },
  { flag:"de" , name:"Germany" },
  { flag:"gh" , name:"Ghana" },
  { flag:"gi" , name:"Gibraltar" },
  { flag:"gr" , name:"Greece" },
  { flag:"gl" , name:"Greenland" },
  { flag:"gd" , name:"Grenada" },
  { flag:"gp" , name:"Guadeloupe" },
  { flag:"gu" , name:"Guam" },
  { flag:"gt" , name:"Guatemala" },
  { flag:"gw" , name:"Guinea-Bissau" },
  { flag:"gn" , name:"Guinea" },
  { flag:"gy" , name:"Guyana" },
  { flag:"ht" , name:"Haiti" },
  { flag:"hm" , name:"Heard Island" },
  { flag:"hn" , name:"Honduras" },
  { flag:"hk" , name:"Hong Kong" },
  { flag:"hu" , name:"Hungary" },
  { flag:"is" , name:"Iceland" },
  { flag:"in" , name:"India" },
  { flag:"io" , name:"Indian Ocean Territory" },
  { flag:"id" , name:"Indonesia" },
  { flag:"ir" , name:"Iran" },
  { flag:"iq" , name:"Iraq" },
  { flag:"ie" , name:"Ireland" },
  { flag:"il" , name:"Israel" },
  { flag:"it" , name:"Italy" },
  { flag:"jm" , name:"Jamaica" },
  { flag:"jp" , name:"Japan" },
  { flag:"jo" , name:"Jordan" },
  { flag:"kz" , name:"Kazakhstan" },
  { flag:"ke" , name:"Kenya" },
  { flag:"ki" , name:"Kiribati" },
  { flag:"kw" , name:"Kuwait" },
  { flag:"kg" , name:"Kyrgyzstan" },
  { flag:"la" , name:"Laos" },
  { flag:"lv" , name:"Latvia" },
  { flag:"lb" , name:"Lebanon" },
  { flag:"ls" , name:"Lesotho" },
  { flag:"lr" , name:"Liberia" },
  { flag:"ly" , name:"Libya" },
  { flag:"li" , name:"Liechtenstein" },
  { flag:"lt" , name:"Lithuania" },
  { flag:"lu" , name:"Luxembourg" },
  { flag:"mo" , name:"Macau" },
  { flag:"mk" , name:"Macedonia" },
  { flag:"mg" , name:"Madagascar" },
  { flag:"mw" , name:"Malawi" },
  { flag:"my" , name:"Malaysia" },
  { flag:"mv" , name:"Maldives" },
  { flag:"ml" , name:"Mali" },
  { flag:"mt" , name:"Malta" },
  { flag:"mh" , name:"Marshall Islands" },
  { flag:"mq" , name:"Martinique" },
  { flag:"mr" , name:"Mauritania" },
  { flag:"mu" , name:"Mauritius" },
  { flag:"yt" , name:"Mayotte" },
  { flag:"mx" , name:"Mexico" },
  { flag:"fm" , name:"Micronesia" },
  { flag:"md" , name:"Moldova" },
  { flag:"mc" , name:"Monaco" },
  { flag:"mn" , name:"Mongolia" },
  { flag:"me" , name:"Montenegro" },
  { flag:"ms" , name:"Montserrat" },
  { flag:"ma" , name:"Morocco" },
  { flag:"mz" , name:"Mozambique" },
  { flag:"na" , name:"Namibia" },
  { flag:"nr" , name:"Nauru" },
  { flag:"np" , name:"Nepal" },
  { flag:"an" , name:"Netherlands Antilles" },
  { flag:"nl" , name:"Netherlands" },
  { flag:"nc" , name:"New Caledonia" },
  { flag:"pg" , name:"New Guinea" },
  { flag:"nz" , name:"New Zealand" },
  { flag:"ni" , name:"Nicaragua" },
  { flag:"ne" , name:"Niger" },
  { flag:"ng" , name:"Nigeria" },
  { flag:"nu" , name:"Niue" },
  { flag:"nf" , name:"Norfolk Island" },
  { flag:"kp" , name:"North Korea" },
  { flag:"mp" , name:"Northern Mariana Islands" },
  { flag:"no" , name:"Norway" },
  { flag:"om" , name:"Oman" },
  { flag:"pk" , name:"Pakistan" },
  { flag:"pw" , name:"Palau" },
  { flag:"ps" , name:"Palestine" },
  { flag:"pa" , name:"Panama" },
  { flag:"py" , name:"Paraguay" },
  { flag:"pe" , name:"Peru" },
  { flag:"ph" , name:"Philippines" },
  { flag:"pn" , name:"Pitcairn Islands" },
  { flag:"pl" , name:"Poland" },
  { flag:"pt" , name:"Portugal" },
  { flag:"pr" , name:"Puerto Rico" },
  { flag:"qa" , name:"Qatar" },
  { flag:"re" , name:"Reunion" },
  { flag:"ro" , name:"Romania" },
  { flag:"ru" , name:"Russia" },
  { flag:"rw" , name:"Rwanda" },
  { flag:"sh" , name:"Saint Helena" },
  { flag:"kn" , name:"Saint Kitts and Nevis" },
  { flag:"lc" , name:"Saint Lucia" },
  { flag:"pm" , name:"Saint Pierre" },
  { flag:"vc" , name:"Saint Vincent" },
  { flag:"ws" , name:"Samoa" },
  { flag:"sm" , name:"San Marino" },
  { flag:"gs" , name:"Sandwich Islands" },
  { flag:"st" , name:"Sao Tome" },
  { flag:"sa" , name:"Saudi Arabia" },
  { flag:"sn" , name:"Senegal" },
  { flag:"cs" , name:"Serbia" },
  { flag:"rs" , name:"Serbia" },
  { flag:"sc" , name:"Seychelles" },
  { flag:"sl" , name:"Sierra Leone" },
  { flag:"sg" , name:"Singapore" },
  { flag:"sk" , name:"Slovakia" },
  { flag:"si" , name:"Slovenia" },
  { flag:"sb" , name:"Solomon Islands" },
  { flag:"so" , name:"Somalia" },
  { flag:"za" , name:"South Africa" },
  { flag:"kr" , name:"South Korea" },
  { flag:"es" , name:"Spain" },
  { flag:"lk" , name:"Sri Lanka" },
  { flag:"sd" , name:"Sudan" },
  { flag:"sr" , name:"Suriname" },
  { flag:"sj" , name:"Svalbard" },
  { flag:"sz" , name:"Swaziland" },
  { flag:"se" , name:"Sweden" },
  { flag:"ch" , name:"Switzerland" },
  { flag:"sy" , name:"Syria" },
  { flag:"tw" , name:"Taiwan" },
  { flag:"tj" , name:"Tajikistan" },
  { flag:"tz" , name:"Tanzania" },
  { flag:"th" , name:"Thailand" },
  { flag:"tl" , name:"Timorleste" },
  { flag:"tg" , name:"Togo" },
  { flag:"tk" , name:"Tokelau" },
  { flag:"to" , name:"Tonga" },
  { flag:"tt" , name:"Trinidad" },
  { flag:"tn" , name:"Tunisia" },
  { flag:"tr" , name:"Turkey" },
  { flag:"tm" , name:"Turkmenistan" },
  { flag:"tv" , name:"Tuvalu" },
  { flag:"ug" , name:"Uganda" },
  { flag:"ua" , name:"Ukraine" },
  { flag:"ae" , name:"United Arab Emirates" },
  { flag:"us" , name:"United States" },
  { flag:"uy" , name:"Uruguay" },
  { flag:"um" , name:"Us Minor Islands" },
  { flag:"vi" , name:"Us Virgin Islands" },
  { flag:"uz" , name:"Uzbekistan" },
  { flag:"vu" , name:"Vanuatu" },
  { flag:"va" , name:"Vatican City" },
  { flag:"ve" , name:"Venezuela" },
  { flag:"vn" , name:"Vietnam" },
  { flag:"wf" , name:"Wallis and Futuna" },
  { flag:"eh" , name:"Western Sahara" },
  { flag:"ye" , name:"Yemen" },
  { flag:"zm" , name:"Zambia" },
  { flag:"zw" , name:"Zimbabwe" }
]
 
export default class Country extends Component {

  componentDidMount(){
    $('.ui.country.dropdown').dropdown({
      onChange: (value) => {
        this.props.handleChange(value);
      }
    });
  }

  componentDidUpdate(){
    $('.ui.country.dropdown').dropdown('refresh');
  }

  render(){
    let items = countries.map(country => {
        return <div className="item" key={country.flag} data-value={country.name}><i className={country.flag + " flag"}></i>{country.name}</div>
      });

    return(
      <div className="ui country fluid search dropdown selection" >
        <input type="hidden" name="country" defaultValue="France"/>
        <i className="dropdown icon"></i>
        <div className="default text">Select Country</div>
        <div className="menu">
          {items}
        </div>
      </div>
    )
  }
}

